using Microsoft.EntityFrameworkCore;
using Mladim.Domain.Enums;
using Mladim.Domain.Models;
using Mladim.Domain.Models.Survey.Questions;

namespace Mladim.Infrastracture.Persistance;

public static class SurveyQuestionSeeder
{
    public static async Task SeedAsync(ApplicationDbContext context)
    {      

        await context.Questions.ExecuteDeleteAsync();
        await context.Database.ExecuteSqlRawAsync("DBCC CHECKIDENT ('[Questions]', RESEED, 0);");        

        var questions = new List<SurveyQuestion>
        {
            // participants 1..7 (Ids will be DB-generated by EF)
            SurveyQuestion.ForParticipant(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Počutila sem se varno in prijetno.","Počutil sem se varno in prijetno.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Bila sem slišana in sprejeta.","Bil sem slišan in sprejet.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Sodelovala sem pri načrtovanju ali izvedbi te aktivnosti/dogodka","Sodeloval sem pri načrtovanju ali izvedbi te aktivnosti/dogodka")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Spodbujena sem bila k aktivni udeležbi.","Spodbujen sem bil k aktivni udeležbi.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Z aktivnostjo sem bila zadovoljna.","Z aktivnostjo sem bil zadovoljen.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Text, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Z eno ali nekaj besedami opiši, kaj si z udeležbo pridobila.","Z eno ali nekaj besedami opiši, kaj si z udeležbo pridobil.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Ali si zaradi svojih telesnih značilnosti, socialnega položaja, narodnosti ali barve kože v slabšem položaju kot večina ostalih?")),

            // group 8..10
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.Group)
                .AddQuestion(GenderText.SameText("Cilji, zaradi katerih smo delovali v skupini, so mi bili jasni.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Rating, SurveyQuestionCategory.Group)
                .AddQuestion(new GenderText("Sodelovala sem pri oblikovanju ciljev skupine in skupinskega dela.","Sodeloval sem pri oblikovanju ciljev skupine in skupinskega dela.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.Group)
                .AddQuestion(new GenderText("Moja pričakovanja, ki sem jih imela od sodelovanja v skupini, so bila jasna in znana drugim (npr.mentorju.)","Moja pričakovanja, ki sem jih imel od sodelovanja v skupini, so bila jasna in znana drugim (npr.mentorju.)")),

            // parent 11 with owned subquestions
            SurveyQuestion.ForParticipant(SurveyQuestionType.Multiple, SurveyQuestionCategory.Group, GenderText.SameText("Zaradi sodelovanja v aktivnosti sem:"))
                .AddQuestion(new GenderText("bolj samozavestna", "bolj samozavesten"))
                .AddQuestion(new GenderText("bolj sposobna delati v skupini", "bolj sposoben delati v skupini"))
                .AddQuestion(GenderText.SameText("se je izboljšal moj učni uspeh"))
                .AddQuestion(GenderText.SameText("lažje branim svoje mnenje"))
                .AddQuestion(GenderText.SameText("verjamem, da je skupaj mogoče doseči pomembne spremembe")),

            // parents 12..15
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.Group)
                .AddQuestion(GenderText.SameText("Mentor ni posegal v delo skupine in v smer, v katero se je razvijalo.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.Group)
                .AddQuestion(GenderText.SameText("Mentor je vzpostavil varen in vključujoč prostor.")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Boolean, SurveyQuestionCategory.Group)
                .AddQuestion(GenderText.SameText("Moja skupina se je redno srečevala (vsaj dvakrat mesečno).")),
            SurveyQuestion.ForParticipant(SurveyQuestionType.Rating, SurveyQuestionCategory.Group)
                .AddQuestion(GenderText.SameText("V skupini smo poleg vsebinskih aktivnosti izvajali tudi aktivnosti, ki so krepile skupino (npr. teambuilding ipd.)")),

            // parent 16 (repetitive) with owned subquestions
            SurveyQuestion.ForParticipant(SurveyQuestionType.MultipleRepetitive, SurveyQuestionCategory.Repetitive, new GenderText("V kolikšni meri si zaradi udeležbe okrepila naslednje sposobnosti:","V kolikšni meri si zaradi udeležbe okrepil naslednje sposobnosti:"))
                .AddQuestion(new GenderText("Sposobna sem se uspešno sporazumevati in povezovati z drugimi.", "Sposoben sem se uspešno sporazumevati in povezovati z drugimi."))
                .AddQuestion(new GenderText("Sposobna sem ustrezno uporabljati različne jezike za sporazumevanje z drugimi.", "Sposoben sem ustrezno uporabljati različne jezike za sporazumevanje z drugimi."))
                .AddQuestion(new GenderText("Sposobna sem uporabljati matematično znanje za reševanje vsakodnevnih izzivov.", "Sposoben sem uporabljati matematično znanje za reševanje vsakodnevnih izzivov."))
                .AddQuestion(new GenderText("Sposobna sem kompetentno uporabljati digitalna orodja pri delu, učenju in stikih z drugimi.", "Sposoben sem kompetentno uporabljati digitalna orodja pri delu, učenju in stikih z drugimi."))
                .AddQuestion(new GenderText("Sposobna sem ohranjati dobro psihično in fizično počutje ter dobre stike z drugimi.", "Sposoben sem ohranjati dobro psihično in fizično počutje ter dobre stike z drugimi."))
                .AddQuestion(new GenderText("Sposobna sem oceniti svoje šibke točke ter tudi pridobiti novo znanje, s katerim jih nadomestim.", "Sposoben sem oceniti svoje šibke točke ter tudi pridobiti novo znanje, s katerim jih nadomestim."))
                .AddQuestion(new GenderText("Sposobna sem delovati kot odgovoren državljan in se polno udeleževati v družbeno in politično življenje.", "Sposoben sem delovati kot odgovoren državljan in se polno udeleževati v družbeno in politično življenje."))
                .AddQuestion(new GenderText("Sposobna sem delovati podjetno in izkoristiti priložnosti, ki se mi ponujajo.", "Sposoben sem delovati podjetno in izkoristiti priložnosti, ki mi ponujajo."))
                .AddQuestion(new GenderText("Odprta sem do različnih kultur in njihovih običajev ter jih tudi spoštujem.", "Odprt sem do različnih kultur in njihovih običajev ter jih tudi spoštujem.")),

            // youth worker parents 17..28
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Z aktivnostjo sem bila zadovoljna.","Z aktivnostjo sem bil zadovoljen.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Vsebine aktivnosti so bile kakovostne.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(new GenderText("Pridobila sem novo znanje, veščine ali vpoglede v mladinsko delo.","Pridobil sem novo znanje, veščine ali vpoglede v mladinsko delo.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Vsebine so bile relevantne za mojo prakso mladinskega dela.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Vsebine so me inspirirale za kakovostno mladinsko delo in delo z mladimi.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Vsebine so me motivirale za nadaljnje delo z mladimi in za mladinsko delo.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Pridobljena znanja, metode ali orodja nameravam uporabiti pri svojem delu in v organizaciji, v kateri delujem.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Text, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Kako je nate vplivala aktivnost in kakšne so spremembe pri tvojem delu zaradi te aktivnosti?")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Text, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Kaj nameravaš zaradi te aktivnosti pri svojem delu narediti drugače ali na novo?")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Text, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Pri katerem delu svojega dela ste uporabili svoja pridobljena znanja?")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Text, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Na kratko opiši, kaj te je (de)motiviralo pri sodelovanju v aktivnosti.")),
            SurveyQuestion.ForYouthWorker(SurveyQuestionType.Rating, SurveyQuestionCategory.General)
                .AddQuestion(GenderText.SameText("Metode dela in podporna orodja (gradiva, materiali) so podpirala moje učenje."))
        };        

        context.Questions.AddRange(questions);
        await context.SaveChangesAsync();
    }
}