// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mladim.Infrastracture.Persistance;

#nullable disable

namespace Mladim.Infrastracture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231022123533_seedSurvey")]
    partial class seedSurvey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityActivityGroup", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.HasKey("ActivitiesId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("ActivityActivityGroup");
                });

            modelBuilder.Entity("ActivityParticipant", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantsId")
                        .HasColumnType("int");

                    b.HasKey("ActivitiesId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("ActivityParticipant");
                });

            modelBuilder.Entity("ActivityPartner", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.Property<int>("PartnersId")
                        .HasColumnType("int");

                    b.HasKey("ActivitiesId", "PartnersId");

                    b.HasIndex("PartnersId");

                    b.ToTable("ActivityPartner");
                });

            modelBuilder.Entity("AppUserOrganization", b =>
                {
                    b.Property<string>("AppUsersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrganizationsId")
                        .HasColumnType("int");

                    b.HasKey("AppUsersId", "OrganizationsId");

                    b.HasIndex("OrganizationsId");

                    b.ToTable("AppUserOrganization");
                });

            modelBuilder.Entity("GroupMember", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.HasKey("GroupsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("GroupMember");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mladim.Domain.IdentityModels.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Mladim.Domain.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyQuestionnairyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SurveyQuestionnairyId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Group");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Member");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Member");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebpageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mladim.Domain.Models.StaffMemberActivity", b =>
                {
                    b.Property<int>("StaffMemberId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.HasKey("StaffMemberId", "ActivityId", "IsLead");

                    b.HasIndex("ActivityId");

                    b.ToTable("StaffMemberActivity");
                });

            modelBuilder.Entity("Mladim.Domain.Models.StaffMemberProject", b =>
                {
                    b.Property<int>("StaffMemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.HasKey("StaffMemberId", "ProjectId", "IsLead");

                    b.HasIndex("ProjectId");

                    b.ToTable("StaffMemberProject");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Questions.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SurveyQuestion");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SurveyQuestion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Responses.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveryResponses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SurveyResponse");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.SurveyQuestionnairy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Questionnairies");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("PartnerProject", b =>
                {
                    b.Property<int>("PartnersId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("PartnersId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("PartnerProject");
                });

            modelBuilder.Entity("ProjectProjectGroup", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("GroupsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("ProjectProjectGroup");
                });

            modelBuilder.Entity("SurveyQuestionSurveyQuestionnairy", b =>
                {
                    b.Property<int>("QuestionsId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyQuestionnairiesId")
                        .HasColumnType("int");

                    b.HasKey("QuestionsId", "SurveyQuestionnairiesId");

                    b.HasIndex("SurveyQuestionnairiesId");

                    b.ToTable("SurveyQuestionSurveyQuestionnairy");

                    b.HasData(
                        new
                        {
                            QuestionsId = 1,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 2,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 3,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 4,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 5,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 6,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 7,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 8,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 9,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 10,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 11,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 12,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 13,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 14,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 15,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 16,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 17,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 18,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 19,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 20,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 21,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 22,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 23,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 24,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 25,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 26,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 27,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 28,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 29,
                            SurveyQuestionnairiesId = 1
                        },
                        new
                        {
                            QuestionsId = 30,
                            SurveyQuestionnairiesId = 1
                        });
                });

            modelBuilder.Entity("Mladim.Domain.Models.ActivityGroup", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Group");

                    b.HasDiscriminator().HasValue("ActivityGroup");
                });

            modelBuilder.Entity("Mladim.Domain.Models.ProjectGroup", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Group");

                    b.HasDiscriminator().HasValue("ProjectGroup");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Participant", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Member");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Participant");
                });

            modelBuilder.Entity("Mladim.Domain.Models.StaffMember", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Member");

                    b.Property<int>("Claim")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("StaffMember");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Questions.FemaleSurveyQuestion", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Survey.Questions.SurveyQuestion");

                    b.HasDiscriminator().HasValue("FemaleSurveyQuestion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Texts = "[\"Po\\u010Dutila sem se varno in prijetno.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Texts = "[\"Bila sem sli\\u0161ana in sprejeta.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Texts = "[\"Sodelovala sem pri na\\u010Drtovanju ali izvedbi te aktivnosti/dogodka\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Texts = "[\"Spodbujena sem bila k aktivni udele\\u017Ebi.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Texts = "[\"Z aktivnostjo sem bila zadovoljna.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Texts = "[\"Z eno ali nekaj besedami opi\\u0161i, kaj si z udele\\u017Ebo pridobila.\"]",
                            Type = 4
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Texts = "[\"Ali si zaradi svojih telesnih zna\\u010Dilnosti, socialnega polo\\u017Eaja, narodnosti ali barve ko\\u017Ee v slab\\u0161em polo\\u017Eaju kot ve\\u010Dina ostalih?\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Texts = "[\"Cilji, zaradi katerih smo delovali v skupini, so mi bili jasni.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Texts = "[\"Sodelovala sem pri oblikovanju ciljev skupine in skupinskega dela.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            Texts = "[\"Moja pri\\u010Dakovanja, ki sem jih imela od sodelovanja v skupini, so bila jasna in znana drugim (npr.mentorju.)\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            Texts = "[\"Zaradi sodelovanja v aktivnosti sem:\",\"bolj samozavestena\",\"bolj sposobna delati v skupini\",\"se je izbolj\\u0161al moj u\\u010Dni uspeh\",\"la\\u017Eje branim svoje mnenje\",\"verjamem, da je skupaj mogo\\u010De dose\\u010Di pomembne spremembe\"]",
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            Texts = "[\"Mentor ni posegal v delo skupine in v smer, v katero se je razvijalo.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            Texts = "[\"Mentor je vzpostavil varen in vklju\\u010Dujo\\u010D prostor.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            Texts = "[\"Moja skupina se je redno sre\\u010Devala (vsaj dvakrat mese\\u010Dno).\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            Texts = "[\"V skupini smo poleg vsebinskih aktivnosti izvajali tudi aktivnosti, ki so krepile skupino (npr. teambuilding ipd.)\"]",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Questions.MaleSurveyQuestion", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Survey.Questions.SurveyQuestion");

                    b.HasDiscriminator().HasValue("MaleSurveyQuestion");

                    b.HasData(
                        new
                        {
                            Id = 16,
                            Category = 1,
                            Texts = "[\"Po\\u010Dutil sem se varno in prijetno.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            Texts = "[\"Bil sem sli\\u0161an in sprejet.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            Category = 1,
                            Texts = "[\"Sodeloval sem pri na\\u010Drtovanju ali izvedbi te aktivnosti/dogodka\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Category = 1,
                            Texts = "[\"Spodbujen sem bil k aktivni udele\\u017Ebi.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Category = 1,
                            Texts = "[\"Z aktivnostjo sem bil zadovoljn.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 21,
                            Category = 1,
                            Texts = "[\"Z eno ali nekaj besedami opi\\u0161i, kaj si z udele\\u017Ebo pridobil.\"]",
                            Type = 4
                        },
                        new
                        {
                            Id = 22,
                            Category = 1,
                            Texts = "[\"Ali si zaradi svojih telesnih zna\\u010Dilnosti, socialnega polo\\u017Eaja, narodnosti ali barve ko\\u017Ee v slab\\u0161em polo\\u017Eaju kot ve\\u010Dina ostalih?\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Category = 2,
                            Texts = "[\"Cilji, zaradi katerih smo delovali v skupini, so mi bili jasni.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Category = 2,
                            Texts = "[\"Sodeloval sem pri oblikovanju ciljev skupine in skupinskega dela.\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            Category = 2,
                            Texts = "[\"Moja pri\\u010Dakovanja, ki sem jih imel od sodelovanja v skupini, so bila jasna in znana drugim (npr.mentorju.)\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Category = 2,
                            Texts = "[\"Zaradi sodelovanja v aktivnosti sem:\",\"bolj samozavesten\",\"bolj sposoben delati v skupini\",\"se je izbolj\\u0161al moj u\\u010Dni uspeh\",\"la\\u017Eje branim svoje mnenje\",\"verjamem, da je skupaj mogo\\u010De dose\\u010Di pomembne spremembe\"]",
                            Type = 3
                        },
                        new
                        {
                            Id = 27,
                            Category = 2,
                            Texts = "[\"Mentor ni posegal v delo skupine in v smer, v katero se je razvijalo.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            Category = 2,
                            Texts = "[\"Mentor je vzpostavil varen in vklju\\u010Dujo\\u010D prostor.\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            Category = 2,
                            Texts = "[\"Moja skupina se je redno sre\\u010Devala (vsaj dvakrat mese\\u010Dno).\"]",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            Category = 2,
                            Texts = "[\"V skupini smo poleg vsebinskih aktivnosti izvajali tudi aktivnosti, ki so krepile skupino (npr. teambuilding ipd.)\"]",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Responses.SurveryBooleanResponse", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Survey.Responses.SurveyResponse");

                    b.Property<int>("Response")
                        .HasColumnType("int");

                    b.ToTable("SurveryResponses", t =>
                        {
                            t.Property("Response")
                                .HasColumnName("SurveryBooleanResponse_Response");
                        });

                    b.HasDiscriminator().HasValue("SurveryBooleanResponse");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Responses.SurveryMultipleResponse", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Survey.Responses.SurveyResponse");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SurveryResponses", t =>
                        {
                            t.Property("Response")
                                .HasColumnName("SurveryMultipleResponse_Response");
                        });

                    b.HasDiscriminator().HasValue("SurveryMultipleResponse");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Responses.SurveryRatingResponse", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Survey.Responses.SurveyResponse");

                    b.Property<int>("Response")
                        .HasColumnType("int");

                    b.ToTable("SurveryResponses", t =>
                        {
                            t.Property("Response")
                                .HasColumnName("SurveryRatingResponse_Response");
                        });

                    b.HasDiscriminator().HasValue("SurveryRatingResponse");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Responses.SurveryTextResponse", b =>
                {
                    b.HasBaseType("Mladim.Domain.Models.Survey.Responses.SurveyResponse");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("SurveryTextResponse");
                });

            modelBuilder.Entity("ActivityActivityGroup", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.ActivityGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityParticipant", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityPartner", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Partner", null)
                        .WithMany()
                        .HasForeignKey("PartnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUserOrganization", b =>
                {
                    b.HasOne("Mladim.Domain.IdentityModels.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMember", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mladim.Domain.IdentityModels.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mladim.Domain.IdentityModels.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.IdentityModels.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mladim.Domain.IdentityModels.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Activity", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Survey.SurveyQuestionnairy", "SurveyQuestionnairy")
                        .WithMany("Activities")
                        .HasForeignKey("SurveyQuestionnairyId");

                    b.OwnsMany("Mladim.Domain.Models.AttachedFile", "Files", b1 =>
                        {
                            b1.Property<int>("ActivityId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FolderName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StoredFileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ActivityId", "Id");

                            b1.ToTable("Activities_Files");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("Mladim.Domain.Models.DateTimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<int>("ActivityId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan?>("EndTime")
                                .HasColumnType("time");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan?>("StartTime")
                                .HasColumnType("time");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("Mladim.Domain.Models.ActivityAttributes", "Attributes", b1 =>
                        {
                            b1.Property<int>("ActivityId")
                                .HasColumnType("int");

                            b1.Property<int>("ActivityTypes")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsGroup")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsMany("Mladim.Domain.Models.AnonymousParticipantGroup", "AnonymousParticipantGroups", b1 =>
                        {
                            b1.Property<int>("ActivityId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.HasKey("ActivityId", "Id");

                            b1.ToTable("AnonymousParticipantGroup");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");

                            b1.OwnsOne("Mladim.Domain.Models.AnonymousParticipant", "AnonymousParticipant", b2 =>
                                {
                                    b2.Property<int>("AnonymousParticipantGroupActivityId")
                                        .HasColumnType("int");

                                    b2.Property<int>("AnonymousParticipantGroupId")
                                        .HasColumnType("int");

                                    b2.Property<int>("AgeGroup")
                                        .HasColumnType("int");

                                    b2.Property<int>("Gender")
                                        .HasColumnType("int");

                                    b2.HasKey("AnonymousParticipantGroupActivityId", "AnonymousParticipantGroupId");

                                    b2.ToTable("AnonymousParticipantGroup");

                                    b2.WithOwner()
                                        .HasForeignKey("AnonymousParticipantGroupActivityId", "AnonymousParticipantGroupId");
                                });

                            b1.Navigation("AnonymousParticipant")
                                .IsRequired();
                        });

                    b.Navigation("AnonymousParticipantGroups");

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Files");

                    b.Navigation("Project");

                    b.Navigation("SurveyQuestionnairy");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Organization", b =>
                {
                    b.OwnsOne("Mladim.Domain.Models.OrganizationAttributes", "Attributes", b1 =>
                        {
                            b1.Property<int>("OrganizationId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("AgeGroups")
                                .HasColumnType("int");

                            b1.Property<string>("BannerUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedStamp")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Fields")
                                .HasColumnType("int");

                            b1.Property<string>("LogoUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("NPMAims")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Regions")
                                .HasColumnType("int");

                            b1.Property<string>("RegistrationNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<int>("Types")
                                .HasColumnType("int");

                            b1.Property<string>("VatNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WebpageUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("YouthSectors")
                                .HasColumnType("int");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("Mladim.Domain.Models.SocialMediaUrls", "SocialMediaUrls", b1 =>
                        {
                            b1.Property<int>("OrganizationId")
                                .HasColumnType("int");

                            b1.Property<string>("Facebook")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Instagram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TikTok")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Twiter")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("SocialMediaUrls")
                        .IsRequired();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Project", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Mladim.Domain.Models.AttachedFile", "Files", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FolderName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StoredFileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectId", "Id");

                            b1.ToTable("Projects_Files");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Mladim.Domain.Models.DateTimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan?>("EndTime")
                                .HasColumnType("time");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan?>("StartTime")
                                .HasColumnType("time");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Mladim.Domain.Models.ProjectAttibutes", "Attributes", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WebpageUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Files");

                    b.Navigation("Organization");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Mladim.Domain.Models.StaffMemberActivity", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Activity", "Activity")
                        .WithMany("Staff")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.StaffMember", "StaffMember")
                        .WithMany("StaffActivities")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Mladim.Domain.Models.StaffMemberProject", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Project", "Project")
                        .WithMany("Staff")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.StaffMember", "StaffMember")
                        .WithMany("StaffProjects")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.Responses.SurveyResponse", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Survey.Questions.SurveyQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PartnerProject", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Partner", null)
                        .WithMany()
                        .HasForeignKey("PartnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectProjectGroup", b =>
                {
                    b.HasOne("Mladim.Domain.Models.ProjectGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SurveyQuestionSurveyQuestionnairy", b =>
                {
                    b.HasOne("Mladim.Domain.Models.Survey.Questions.SurveyQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mladim.Domain.Models.Survey.SurveyQuestionnairy", null)
                        .WithMany()
                        .HasForeignKey("SurveyQuestionnairiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mladim.Domain.Models.Activity", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Organization", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Project", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Mladim.Domain.Models.Survey.SurveyQuestionnairy", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Mladim.Domain.Models.StaffMember", b =>
                {
                    b.Navigation("StaffActivities");

                    b.Navigation("StaffProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
